### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marklester-cymra** [Human018/laravel-aus-post#1]
Hi I'm directly integration AusPost to my Laravel Project, is there any documentation of this?

**Comment by Human018** [comment]
Hi Mark, I haven't written any docs for it, but most of the logic is happening in the Human018\LaravelAusPost\AusPost class.

It's a fluent class allowing you to set the shipping parameters and get an array response.

Here is an example of how I have used it in my projects:
`$result = AusPost::domestic()->parcelCalculate()->fromPostcode(...)
                ->toPostcode(...)
                ->length($lengthInMillimetres)->width($widthInMillimetres)->height($heightInMillimetres)
                ->weight($weightInGrams)->usingService('AUS_PARCEL_EXPRESS')->get();`

**Comment by Human018** [comment]
> Hi I'm directly integration AusPost to my Laravel Project, is there any documentation of this?

I've added some preliminary documentation to the package

**Comment by marklester-cymra** [comment]
> Hi Mark, I haven't written any docs for it, but most of the logic is happening in the Human018\LaravelAusPost\AusPost class.
> 
> It's a fluent class allowing you to set the shipping parameters and get an array response.
> 
> Here is an example of how I have used it in my projects: `$result = AusPost::domestic()->parcelCalculate()->fromPostcode(...) ->toPostcode(...) ->length($lengthInMillimetres)->width($widthInMillimetres)->height($heightInMillimetres) ->weight($weightInGrams)->usingService('AUS_PARCEL_EXPRESS')->get();`

Thanks Bud!
